# AerospikeService Configuration
# This file contains configuration for connecting to Aerospike databases

default: &default
  # List of Aerospike hosts to connect to
  hosts:
    - host: "127.0.0.1"
      port: 3000
    # You can also use the simpler string format:
    # - "127.0.0.1:3000"
  
  # List of available namespaces
  namespaces:
    - test
    - development
  
  # Default namespace to use when not specified
  default_namespace: test
  
  # Connection timeouts (in seconds)
  connection_timeout: 1.0
  socket_timeout: 0.5
  total_timeout: 2.0
  
  # Connection pool settings
  pool_size: 5        # Number of connections in the pool
  pool_timeout: 5.0   # Timeout for acquiring a connection from the pool

# Development environment
development:
  <<: *default

# Test environment
test:
  <<: *default
  hosts:
    - host: "127.0.0.1"
      port: 3000

# Production environment
production:
  <<: *default
  hosts:
    - host: <%= ENV['AEROSPIKE_HOST'] || '127.0.0.1' %>
      port: <%= ENV['AEROSPIKE_PORT'] || 3000 %>
  default_namespace: <%= ENV['AEROSPIKE_NAMESPACE'] || 'production' %>
  connection_timeout: 2.0
  socket_timeout: 1.0
  total_timeout: 5.0
  pool_size: <%= ENV['AEROSPIKE_POOL_SIZE'] || 10 %>
  pool_timeout: <%= ENV['AEROSPIKE_POOL_TIMEOUT'] || 5.0 %>