test:
  default_namespace: userdata
  namespaces:
    userdata:
      zk_path: "/limeroad/aerospike/userdata"
    userdata_nc:
      zk_path: "/limeroad/aerospike/userdata_nc"
    userdata_mem_nc:
      zk_path: "/limeroad/aerospike/userdata_mem_nc"
  connect_timeout: 1.0
  timeout: 1.0
  max_retries: 2
  max_connections: 10
