version: 2
updates:
- package-ecosystem: bundler
  directory: "/aerospike"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
