# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in aerospike_service.gemspec
gemspec

# Development dependencies
gem "rake", "~> 13.0"
gem "rspec", "~> 3.12"
gem "simplecov", "~> 0.22"
gem "yard", "~> 0.9"
gem "pry", "~> 0.14"
