name: Aerospike CI

on:
  pull_request:
    paths:
      - 'aerospike/**'
      - '.github/workflows/aerospike-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'aerospike/**'
      - '.github/workflows/aerospike-ci.yml'

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: aerospike
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Format code
        run: bundle exec standardrb --fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-format Ruby code with Standard"
          branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

  lint:
    needs: format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aerospike
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec standardrb --no-fix
